SHOPPING DATASET CLEANING

Step 1 - Load Dataset

In [2]:
import pandas as pd

df = pd.read_csv('Combined_dataset.csv')
print("Dataset loaded successfully!")

Dataset loaded successfully!

Step 2 - EDA(Exploratory Data Analysis)

In [3]:
# First 5 rows — quick look at the data
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
# Last 5 rows — check if data is consistent at the end
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [5]:
# Shape — how big is this dataset?
print("Shape:", df.shape)
print(f"{df.shape[0]} rows and {df.shape[1]} columns")

Shape: (1000, 24)
1000 rows and 24 columns

In [6]:
# Column names
print("Columns:", df.columns.tolist())

Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [7]:
# Data types of each column
# object = text/string, int64 = whole numbers, float64 = decimal numbers
print(df.dtypes)

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [8]:
# df.info() —Shows column names, how many non-null values exist, and data types
# If Non-Null Count < total rows → that column has missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   str
 2   product_description     1000 non-null   str
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   str
 8   currency                1000 non-null   str
 9   images                  1000 non-null   str
 10  delivery_options        1000 non-null   str
 11  product_details         1000 non-null   str
 12  breadcrumbs             1000 non-null   str
 13  product_specifications  1000 non-null   str
 14  amount_of_stars         1000 non-null   str
 15  what_customers_said     427 non-null    str
 16  seller_name             699 non-null    str
 17  sizes                   1000 non-null   str
 18  videos                  219 non-null    str
 19  seller_information      699 non-null    str
 20  variations              438 non-null    str
 21  best_offer              1000 non-null   str
 22  more_offers             1000 non-null   str
 23  category                1000 non-null   str
dtypes: float64(2), int64(3), str(19)
memory usage: 187.6 KB

In [9]:
# Statistical summary — only for numeric columns
# Shows count, mean, std, min, max, and percentiles
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [10]:
# Unique categories in the dataset
print("Categories:")
print(df['category'].value_counts())

Categories:
category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
               ...
tights            1
towel-set         1
trolley-bag       1
wall-art          1
yoga-mats         1
Name: count, Length: 97, dtype: int64

In [11]:
# Unique values per column — useful for finding messy columns
for col in df.columns:
    print(f"  {col:<30}: {df[col].nunique()} unique values")

  product_id                    : 1000 unique values
  title                         : 454 unique values
  product_description           : 989 unique values
  rating                        : 34 unique values
  ratings_count                 : 221 unique values
  initial_price                 : 256 unique values
  discount                      : 81 unique values
  final_price                   : 466 unique values
  currency                      : 1 unique values
  images                        : 1000 unique values
  delivery_options              : 16 unique values
  product_details               : 998 unique values
  breadcrumbs                   : 658 unique values
  product_specifications        : 967 unique values
  amount_of_stars               : 808 unique values
  what_customers_said           : 302 unique values
  seller_name                   : 301 unique values
  sizes                         : 672 unique values
  videos                        : 219 unique values
  seller_information            : 298 unique values
  variations                    : 22 unique values
  best_offer                    : 468 unique values
  more_offers                   : 159 unique values
  category                      : 97 unique values

Step 3 - Handling Missing values

In [12]:
# Check missing values
print("Missing values per column:")
print(df.isnull().sum())
print(f"\nTotal missing: {df.isnull().sum().sum()}")

Missing values per column:
product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

Total missing: 2639

In [32]:
# Fix final_price — it's stored as str, convert to numeric
# errors='coerce' turns any non-numeric value (like '$' or '-') into NaN
# Fix final_price — remove currency symbols and commas first, then convert
df['final_price'] = df['final_price'].astype(str).str.replace('₹', '').str.replace(',', '').str.strip()
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

print("'final_price' converted to numeric ")
print("dtype now:", df['final_price'].dtype)
print(df['final_price'].head())

'final_price' converted to numeric
dtype now: float64
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: final_price, dtype: float64

In [14]:
# Fill missing numeric values with median
# Median is better than mean (not affected by extreme prices)

for col in ['initial_price', 'final_price', 'rating', 'discount']:
    if df[col].isnull().sum() > 0:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)
        print(f"  '{col}' — filled {df[col].isnull().sum()} nulls with median ({median_val:.2f})")

  'final_price' — filled 1000 nulls with median (nan)
  'discount' — filled 0 nulls with median (56.00)

In [15]:
# Fill missing text columns with 'Unknown'
text_fill_cols = ['seller_name', 'category', 'sizes', 'currency']

for col in text_fill_cols:
    if df[col].isnull().sum() > 0:
        n = df[col].isnull().sum()
        df[col] = df[col].fillna('Unknown')
        print(f"  '{col}' — filled {n} nulls with 'Unknown'")

  'seller_name' — filled 301 nulls with 'Unknown'

In [16]:
# Confirm
print("Missing values after cleaning:")
print(df.isnull().sum()[df.isnull().sum() > 0])
print(f"\nTotal nulls remaining: {df.isnull().sum().sum()}")

Missing values after cleaning:
final_price            1000
what_customers_said     573
videos                  781
seller_information      301
variations              562
dtype: int64

Total nulls remaining: 3217

Step 4 - Filter Rows & selet columns

In [17]:
# Select useful columns only
useful_cols = ['product_id', 'title', 'category', 'rating',
               'ratings_count', 'initial_price', 'discount',
               'final_price', 'seller_name', 'sizes']

df_clean = df[useful_cols]
df_clean.head()

,product_id,title,category,rating,ratings_count,initial_price,discount,final_price,seller_name,sizes
0,8376765,Lino Perros,backpacks,3.8,15,3995,58.0,NaN,Unknown,"[{""size"":""Onesize""}]"
1,9136281,Tommy Hilfiger,backpacks,4.5,67,2899,35.0,NaN,Unknown,"[{""size"":""Onesize""}]"
2,17633752,Lavie,backpacks,4.4,226,2999,65.0,NaN,Unknown,"[{""size"":""S""}]"
3,1376949,F Gear,backpacks,4.4,1052,1675,52.0,NaN,Unknown,"[{""size"":""Onesize""}]"
4,13939916,MYTRIDENT,bath-robe,4.7,12,2899,17.0,NaN,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr..."

In [18]:
# Filter — products with rating above 4.0
high_rated = df_clean[df_clean['rating'] > 4.0]
print(f"High rated products (>4.0): {len(high_rated)}")
high_rated.head()

High rated products (>4.0): 533

,product_id,title,category,rating,ratings_count,initial_price,discount,final_price,seller_name,sizes
1,9136281,Tommy Hilfiger,backpacks,4.5,67,2899,35.0,NaN,Unknown,"[{""size"":""Onesize""}]"
2,17633752,Lavie,backpacks,4.4,226,2999,65.0,NaN,Unknown,"[{""size"":""S""}]"
3,1376949,F Gear,backpacks,4.4,1052,1675,52.0,NaN,Unknown,"[{""size"":""Onesize""}]"
4,13939916,MYTRIDENT,bath-robe,4.7,12,2899,17.0,NaN,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr..."
5,17198778,H&M,bathroom-accessories,4.5,42,1399,56.0,NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]"

In [19]:
# Filter — products with discount above 20%
high_discount = df_clean[df_clean['discount'] > 20]
print(f"Products with >20% discount: {len(high_discount)}")
high_discount.head()

Products with >20% discount: 941

,product_id,title,category,rating,ratings_count,initial_price,discount,final_price,seller_name,sizes
0,8376765,Lino Perros,backpacks,3.8,15,3995,58.0,NaN,Unknown,"[{""size"":""Onesize""}]"
1,9136281,Tommy Hilfiger,backpacks,4.5,67,2899,35.0,NaN,Unknown,"[{""size"":""Onesize""}]"
2,17633752,Lavie,backpacks,4.4,226,2999,65.0,NaN,Unknown,"[{""size"":""S""}]"
3,1376949,F Gear,backpacks,4.4,1052,1675,52.0,NaN,Unknown,"[{""size"":""Onesize""}]"
5,17198778,H&M,bathroom-accessories,4.5,42,1399,56.0,NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]"

In [20]:
# Combined filter — high rating AND high discount
good_deal = df_clean[(df_clean['rating'] > 4.0) & (df_clean['discount'] > 20)]
print(f"High rated + high discount: {len(good_deal)}")
good_deal.head()

High rated + high discount: 498

,product_id,title,category,rating,ratings_count,initial_price,discount,final_price,seller_name,sizes
1,9136281,Tommy Hilfiger,backpacks,4.5,67,2899,35.0,NaN,Unknown,"[{""size"":""Onesize""}]"
2,17633752,Lavie,backpacks,4.4,226,2999,65.0,NaN,Unknown,"[{""size"":""S""}]"
3,1376949,F Gear,backpacks,4.4,1052,1675,52.0,NaN,Unknown,"[{""size"":""Onesize""}]"
5,17198778,H&M,bathroom-accessories,4.5,42,1399,56.0,NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]"
7,18602872,My Room,bedsheets,4.7,10,2999,54.0,NaN,Unknown,"[{""size"":""Single""},{""size"":""Double Queen""},{""s..."

Step 5 - Remove duplicates
# Check for duplicates based on 'product_id'

In [21]:
print(f"Duplicate rows found: {df_clean.duplicated().sum()}")

Duplicate rows found: 0

In [22]:
print(f"Rows before: {len(df_clean)}")

df_clean = df_clean.drop_duplicates(keep='first')
df_clean = df_clean.reset_index(drop=True)

print(f"Rows after:  {len(df_clean)}")
print("Duplicates removed ✅")

Rows before: 1000
Rows after:  1000
Duplicates removed ✅

Step 6 - Derived Columns

In [23]:
# savings = how much money the customer saves per product
# This replaces total_amount = price × quantity (no quantity column in this dataset)

df_clean['savings'] = df_clean['initial_price'] - df_clean['final_price']

print("'savings' column created ✅")
df_clean[['title', 'initial_price', 'final_price', 'discount', 'savings']].head(8)

'savings' column created ✅

            title  initial_price  final_price  discount  savings
0     Lino Perros           3995          NaN      58.0      NaN
1  Tommy Hilfiger           2899          NaN      35.0      NaN
2           Lavie           2999          NaN      65.0      NaN
3          F Gear           1675          NaN      52.0      NaN
4       MYTRIDENT           2899          NaN      17.0      NaN
5             H&M           1399          NaN      56.0      NaN
6      AVI Living           1399          NaN      65.0      NaN
7         My Room           2999          NaN      54.0      NaN

In [24]:
# Insights from the new column
print(f"Average savings per product : ₹{df_clean['savings'].mean():,.2f}")
print(f"Maximum savings             : ₹{df_clean['savings'].max():,.2f}")
print(f"Minimum savings             : ₹{df_clean['savings'].min():,.2f}")

Average savings per product : ₹nan
Maximum savings             : ₹nan
Minimum savings             : ₹nan

In [25]:
# Average savings by category
print("Average Savings by Category:")
print(df_clean.groupby('category')['savings']
      .mean()
      .sort_values(ascending=False)
      .round(2))

Average Savings by Category:
category
backpacks              NaN
bath-robe              NaN
bath-towels            NaN
bathroom-accessories   NaN
bedsheets              NaN
                        ..
tunics                 NaN
wall-art               NaN
wallets                NaN
watches                NaN
yoga-mats              NaN
Name: savings, Length: 97, dtype: float64

Final Step - Save the dataset

In [26]:
df_clean.to_csv('cleaned_shopping_dataset.csv', index=False)

print("Saved as 'cleaned_shopping_dataset.csv' ✅")
print(f"Final shape: {df_clean.shape[0]} rows × {df_clean.shape[1]} columns")

Saved as 'cleaned_shopping_dataset.csv' ✅
Final shape: 1000 rows × 11 columns