Creating and connecting to the database

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('shopease.db')
cursor = conn.cursor()

# Enable foreign key enforcement
# In SQLite this must be set every time a new connection is opened
cursor.execute("PRAGMA foreign_keys = ON;")

print("Connection successful!")

Connection successful!

Creating Tables

In [2]:
# I used CREATE IF NOT EXISTS to avoid errors if the tables already exist.
# This allows us to run the script multiple times without issues.


cursor.executescript("""

-- customers table
CREATE TABLE IF NOT EXISTS customers (
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    join_date DATE NOT NULL,
    is_premium BOOLEAN DEFAULT FALSE
);

-- products table
CREATE TABLE IF NOT EXISTS products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL CHECK (unit_price > 0),
    stock_qty INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0)
);

-- orders table
CREATE TABLE IF NOT EXISTS orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending','Shipped','Delivered','Cancelled')),
    total_amount DECIMAL(12,2) NOT NULL CHECK (total_amount >= 0),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- order_items table
CREATE TABLE IF NOT EXISTS order_items (
    item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(10,2) NOT NULL CHECK (unit_price > 0),
    discount_pct DECIMAL(5,2) DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100),
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

""")

conn.commit()
print("All tables created successfully!")

All tables created successfully!

Creating Indexes in each table

In [3]:
cursor.executescript("""

-- Indexes on customers
CREATE INDEX IF NOT EXISTS idx_customers_city ON customers(city);
CREATE INDEX IF NOT EXISTS idx_customers_state ON customers(state);

-- Index on products
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);

-- Indexes on orders
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(order_date);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

""")

conn.commit()
print("All indexes created successfully!")

All indexes created successfully!

Inserting Data into the tables

In [4]:
# I used INSERT OR IGNORE to avoid duplicate entries if the script is run multiple times.

cursor.executescript("""

-- customers
INSERT OR IGNORE INTO customers VALUES
(101,'Aarav','Sharma','aarav.s@email.com','Mumbai','Maharashtra','2024-01-15',1),
(102,'Priya','Patel','priya.p@email.com','Ahmedabad','Gujarat','2024-02-20',0),
(103,'Rohan','Gupta','rohan.g@email.com','Delhi','Delhi','2024-03-10',1),
(104,'Sneha','Reddy','sneha.r@email.com','Hyderabad','Telangana','2024-04-05',0),
(105,'Vikram','Singh','vikram.s@email.com','Jaipur','Rajasthan','2024-05-12',1),
(106,'Ananya','Iyer','ananya.i@email.com','Chennai','Tamil Nadu','2024-06-18',0),
(107,'Karan','Mehta','karan.m@email.com','Pune','Maharashtra','2024-07-22',1),
(108,'Divya','Nair','divya.n@email.com','Kochi','Kerala','2024-08-30',0);

-- products
INSERT OR IGNORE INTO products VALUES
(201,'Wireless Earbuds','Electronics','BoAt',1499.00,250),
(202,'Cotton T-Shirt','Clothing','Levis',799.00,500),
(203,'Smart Watch','Electronics','Noise',2999.00,150),
(204,'Running Shoes','Clothing','Nike',4599.00,120),
(205,'Bluetooth Speaker','Electronics','JBL',3499.00,200),
(206,'Bedsheet Set','Home','Spaces',1299.00,300),
(207,'Laptop Stand','Electronics','AmazonBasics',899.00,180),
(208,'Cushion Covers (Set)','Home','HomeCenter',599.00,400);

-- orders
INSERT OR IGNORE INTO orders VALUES
(1001,101,'2024-08-01','Delivered',4498.00),
(1002,102,'2024-08-03','Delivered',799.00),
(1003,103,'2024-08-05','Shipped',7498.00),
(1004,101,'2024-08-10','Delivered',3499.00),
(1005,104,'2024-08-12','Cancelled',2999.00),
(1006,105,'2024-08-15','Delivered',5898.00),
(1007,106,'2024-08-18','Pending',1299.00),
(1008,103,'2024-08-20','Delivered',899.00),
(1009,107,'2024-08-25','Shipped',6098.00),
(1010,108,'2024-08-28','Delivered',1598.00);

-- order_items
INSERT OR IGNORE INTO order_items VALUES
(5001,1001,201,2,1499.00,0),
(5002,1001,207,1,899.00,10),
(5003,1002,202,1,799.00,0),
(5004,1003,203,1,2999.00,0),
(5005,1003,204,1,4599.00,5),
(5006,1004,205,1,3499.00,0),
(5007,1005,203,1,2999.00,0),
(5008,1006,201,1,1499.00,10),
(5009,1006,204,1,4599.00,5),
(5010,1007,206,1,1299.00,0),
(5011,1008,207,1,899.00,0),
(5012,1009,205,1,3499.00,0),
(5013,1009,208,2,599.00,15),
(5014,1010,206,1,1299.00,0),
(5015,1010,208,1,599.00,0);

""")

conn.commit()
print("All data inserted successfully!")

All data inserted successfully!

Verifying Data loading

In [5]:
# Dynamically checking row counts for all tables to confirm correct data insertion
tables = ['customers', 'products', 'orders', 'order_items']

for table in tables:
    count = pd.read_sql_query(f"SELECT COUNT(*) as row_count FROM {table}", conn)
    print(f"{table}: {count['row_count'][0]} rows")


# Check column names in each table by limiting to 0 rows to get only the schema
print("\n--- Column Names ---")
for table in tables:
    columns = pd.read_sql_query(f"SELECT * FROM {table} LIMIT 0", conn).columns.tolist()
    print(f"{table}: {columns}")

# check the data 
print("\n--- Data ---")
for table in tables:
    data = pd.read_sql_query(f"SELECT * FROM {table}", conn)
    print(f"\n{table} sample data:")
    print(data)

customers: 8 rows
products: 8 rows
orders: 11 rows
order_items: 17 rows

--- Column Names ---
customers: ['customer_id', 'first_name', 'last_name', 'email', 'city', 'state', 'join_date', 'is_premium']
products: ['product_id', 'product_name', 'category', 'brand', 'unit_price', 'stock_qty']
orders: ['order_id', 'customer_id', 'order_date', 'status', 'total_amount']
order_items: ['item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount_pct']

--- Data ---

customers sample data:
   customer_id first_name last_name               email       city  \
0          101      Aarav    Sharma   aarav.s@email.com     Mumbai
1          102      Priya     Patel   priya.p@email.com  Ahmedabad
2          103      Rohan     Gupta   rohan.g@email.com      Delhi
3          104      Sneha     Reddy   sneha.r@email.com  Hyderabad
4          105     Vikram     Singh  vikram.s@email.com     Jaipur
5          106     Ananya      Iyer  ananya.i@email.com    Chennai
6          107      Karan     Mehta   karan.m@email.com       Pune
7          108      Divya      Nair   divya.n@email.com      Kochi

         state   join_date  is_premium
0  Maharashtra  2024-01-15           1
1      Gujarat  2024-02-20           0
2        Delhi  2024-03-10           1
3    Telangana  2024-04-05           0
4    Rajasthan  2024-05-12           1
5   Tamil Nadu  2024-06-18           0
6  Maharashtra  2024-07-22           1
7       Kerala  2024-08-30           0

products sample data:
   product_id          product_name     category         brand  unit_price  \
0         201      Wireless Earbuds  Electronics          BoAt        1499
1         202        Cotton T-Shirt     Clothing         Levis         799
2         203           Smart Watch  Electronics         Noise        2999
3         204         Running Shoes     Clothing          Nike        4599
4         205     Bluetooth Speaker  Electronics           JBL        3499
5         206          Bedsheet Set         Home        Spaces        1299
6         207          Laptop Stand  Electronics  AmazonBasics         899
7         208  Cushion Covers (Set)         Home    HomeCenter         599

   stock_qty
0        250
1        498
2        150
3        120
4        200
5        300
6        180
7        400

orders sample data:
    order_id  customer_id  order_date     status  total_amount
0       1001          101  2024-08-01  Delivered          4498
1       1002          102  2024-08-03  Delivered           799
2       1003          103  2024-08-05    Shipped          7498
3       1004          101  2024-08-10  Delivered          3499
4       1005          104  2024-08-12  Cancelled          2999
5       1006          105  2024-08-15  Delivered          5898
6       1007          106  2024-08-18    Pending          1299
7       1008          103  2024-08-20  Delivered           899
8       1009          107  2024-08-25    Shipped          6098
9       1010          108  2024-08-28  Delivered          1598
10      1011          102  2026-06-08    Pending          1598

order_items sample data:
    item_id  order_id  product_id  quantity  unit_price  discount_pct
0      5001      1001         201         2        1499             0
1      5002      1001         207         1         899            10
2      5003      1002         202         1         799             0
3      5004      1003         203         1        2999             0
4      5005      1003         204         1        4599             5
5      5006      1004         205         1        3499             0
6      5007      1005         203         1        2999             0
7      5008      1006         201         1        1499            10
8      5009      1006         204         1        4599             5
9      5010      1007         206         1        1299             0
10     5011      1008         207         1         899             0
11     5012      1009         205         1        3499             0
12     5013      1009         208         2         599            15
13     5014      1010         206         1        1299             0
14     5015      1010         208         1         599             0
15     5016      1011         202         1         799             0
16     5017      1011         202         1         799             0

SECTION A

Q1. Write a query to display all columns and rows from the customer's table

In [6]:
df_q1 = pd.read_sql_query("SELECT * FROM customers", conn)
df_q1.index += 1

# Verify: column count should be exactly 8 and rows should be exactly 8
print(f"Columns returned: {list(df_q1.columns)}")
print(f"Rows returned: {len(df_q1)}") 

df_q1

Columns returned: ['customer_id', 'first_name', 'last_name', 'email', 'city', 'state', 'join_date', 'is_premium']
Rows returned: 8

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
1,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
2,102,Priya,Patel,priya.p@email.com,Ahmedabad,Gujarat,2024-02-20,0
3,103,Rohan,Gupta,rohan.g@email.com,Delhi,Delhi,2024-03-10,1
4,104,Sneha,Reddy,sneha.r@email.com,Hyderabad,Telangana,2024-04-05,0
5,105,Vikram,Singh,vikram.s@email.com,Jaipur,Rajasthan,2024-05-12,1
6,106,Ananya,Iyer,ananya.i@email.com,Chennai,Tamil Nadu,2024-06-18,0
7,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1
8,108,Divya,Nair,divya.n@email.com,Kochi,Kerala,2024-08-30,0

**Insight**- 

The customers table has 8 records spanning 7 different Indian states. 
4 customers are premium (is_premium = 1) and 4 are non-premium. 
All records are complete with no NULL values.

Q2. Retrieve only the first_name, last_name, and city of all customers.

In [7]:
df_q2 = pd.read_sql_query("SELECT first_name, last_name, city FROM customers", conn)
df_q2.index += 1

# Verify: column count should be exactly 3
print(f"Columns returned: {list(df_q2.columns)}")
print(f"Rows returned: {len(df_q2)}")

df_q2

Columns returned: ['first_name', 'last_name', 'city']
Rows returned: 8

  first_name last_name       city
1      Aarav    Sharma     Mumbai
2      Priya     Patel  Ahmedabad
3      Rohan     Gupta      Delhi
4      Sneha     Reddy  Hyderabad
5     Vikram     Singh     Jaipur
6     Ananya      Iyer    Chennai
7      Karan     Mehta       Pune
8      Divya      Nair      Kochi

Q3. List all unique categories available in the products table.

In [8]:
df_q3 = pd.read_sql_query("SELECT DISTINCT category FROM products", conn)
df_q3.index += 1

# Verify: compare DISTINCT categories vs total products
total_products = pd.read_sql_query("SELECT COUNT(*) as total FROM products", conn)
total_categories = pd.read_sql_query("SELECT COUNT(DISTINCT category) as total FROM products", conn)
print(f"Total products: {total_products['total'][0]}")
print(f"Unique categories: {total_categories['total'][0]}")


df_q3

Total products: 8
Unique categories: 3

      category
1     Clothing
2  Electronics
3         Home

**Insight**- ShopEase sells across 3 categories — Electronics, Clothing, and Home. 
Electronics has the most products (4 out of 8), suggesting it is the primary focus area.

Q4. Identify the Primary Key of each table in the schema. Explain why a Primary Key must be unique and NOT NULL.

In [9]:
# Dynamically fetch primary key info for all tables using PRAGMA
tables = ['customers', 'products', 'orders', 'order_items']

for table in tables:
# pk_info creates a dataframe with schema information for a table
    pk_info = pd.read_sql_query(f"PRAGMA table_info({table})", conn)

# pk_col filters the dataframe to find the column where 'pk' is 1, 
# indicating it's the primary key, and selects its name and type
    pk_col = pk_info[pk_info['pk'] == 1][['name', 'type']]
    print(f"Table: {table}")

# gets name and type of primary key column and prints it(its at index 0)
    print(f"  Primary Key: {pk_col['name'].values[0]} ({pk_col['type'].values[0]})")
    print()

Table: customers
  Primary Key: customer_id (INT)

Table: products
  Primary Key: product_id (INT)

Table: orders
  Primary Key: order_id (INT)

Table: order_items
  Primary Key: item_id (INT)

**Explaination**

Why must a Primary Key be UNIQUE and NOT NULL?

- UNIQUE: A Primary Key identifies one specific row. If two rows had the 
same customer_id, the database would not know which customer an order belongs to — 
leading to wrong or ambiguous query results.

- NOT NULL: If customer_id were NULL, that customer cannot be referenced 
from the orders table via Foreign Key. A NULL PK means the row has no identity — 
it cannot be reliably found, updated, or deleted.

Q5. What constraints are applied to the email column in the customers table? What would happen if you tried to insert a duplicate email?

In [10]:
# Checking the customers table structure
# this tells that the email column cannot be NULL and as defined in the schema,
# It is a UNIQUE constraint.
email_info = pd.read_sql_query("PRAGMA table_info(customers)", conn)
email_row = email_info[email_info['name'] == 'email']
print("Email column definition:")
print(email_row[['name', 'type', 'notnull', 'dflt_value', 'pk']].to_string(index=False))

Email column definition:
 name         type  notnull dflt_value  pk
email VARCHAR(100)        1        NaN   0

In [11]:
# For verification — trying to insert a duplicate email
try:
    cursor.execute("""
        INSERT INTO customers VALUES 
        (109, 'Test', 'User', 'aarav.s@email.com', 'Mumbai', 'Maharashtra', '2024-09-01', 0)
    """)
    conn.commit()
    print("Insert succeeded")
except Exception as e:
    print(f"Insert failed")
    print(f"Error: {e}")

Insert failed
Error: UNIQUE constraint failed: customers.email

**Reason of happening**

Constraints on the email column:

1. UNIQUE — No two customers can share the same email address. 
   Each email identifies exactly one customer account.

2. NOT NULL — Every customer must have an email. 
   A customer record without an email is incomplete and cannot be created.

What happens on duplicate insert?
SQLite raises:  
'UNIQUE constraint failed: customers.email'  
The entire INSERT is rejected — no partial data is written.

What is the use? 
Email is used for order confirmations, login, and marketing. 
A duplicate email would mean two accounts receiving each other's order updates
which creates a data integrity issue.

Q6. Try inserting a product with unit_price = -50. What happens and which constraint prevents it? Write both the INSERT statement and explain the error.

In [12]:
# Trying to insert a product with negative unit_price

try:
    cursor.execute("""
        INSERT INTO products VALUES 
        (209, 'Test Product', 'Electronics', 'TestBrand', -50.00, 100)
    """)
    conn.commit()
    print("Insert succeeded ")
except Exception as e:
    print(f"Insert failed ")
    print(f"Error: {e}")

Insert failed
Error: CHECK constraint failed: unit_price > 0

**What goes behind?**

What constraint prevents this?
unit_price DECIMAL(10,2) NOT NULL CHECK (unit_price > 0)
The 'CHECK (unit_price > 0)' constraint rejects any value that is zero or negative.

Error thrown:
'CHECK constraint failed: products'

What is the use of this constraint?
Without this constraint, a data entry error could insert 
a product with price -50, which would:
- Reduce total revenue calculations incorrectly
- Cause negative order amounts
- Break business logic that assumes prices are always positive

SECTION B

 

Q7. Retrieve all orders with status = 'Delivered'.

In [13]:
df_q7 = pd.read_sql_query("""
    SELECT * 
    FROM orders
    WHERE status = 'Delivered'
""", conn)
df_q7.index += 1

# Verifying : count of delivered vs total orders
total = pd.read_sql_query("SELECT COUNT(*) as total FROM orders", conn)
delivered = pd.read_sql_query("SELECT COUNT(*) as delivered FROM orders WHERE status = 'Delivered'", conn)
print(f"Total orders: {total['total'][0]}")
print(f"Delivered orders: {delivered['delivered'][0]}")
print(f"Delivery rate: {round(delivered['delivered'][0] / total['total'][0] * 100, 1)}%")

df_q7

Total orders: 11
Delivered orders: 6
Delivery rate: 54.5%

   order_id  customer_id  order_date     status  total_amount
1      1001          101  2024-08-01  Delivered          4498
2      1002          102  2024-08-03  Delivered           799
3      1004          101  2024-08-10  Delivered          3499
4      1006          105  2024-08-15  Delivered          5898
5      1008          103  2024-08-20  Delivered           899
6      1010          108  2024-08-28  Delivered          1598

**Insight**- Out of 10 total orders, 6 have been delivered — a 60% delivery rate.
The remaining orders are either Shipped, Pending, or Cancelled.
This is a good fulfillment rate for an e-commerce platform.

Q8. Find all products in the 'Electronics' category with a unit_price greater than ₹2000.

In [14]:
df_q8 = pd.read_sql_query("""
    SELECT product_id, product_name, brand, unit_price
    FROM products
    WHERE category = 'Electronics'
    AND unit_price > 2000
    ORDER BY unit_price DESC
""", conn)
df_q8.index += 1

df_q8

   product_id       product_name  brand  unit_price
1         205  Bluetooth Speaker    JBL        3499
2         203        Smart Watch  Noise        2999

In [15]:

# Verifying: to check that all electronics are fil correctly
all_electronics = pd.read_sql_query("""
    SELECT product_name, unit_price,
           CASE
                WHEN unit_price > 2000 THEN 'Included' 
                ELSE 'Excluded' 
            END as in_result
    FROM products
    WHERE category = 'Electronics'
    ORDER BY unit_price DESC
""", conn)
all_electronics.index += 1
all_electronics

        product_name  unit_price in_result
1  Bluetooth Speaker        3499  Included
2        Smart Watch        2999  Included
3   Wireless Earbuds        1499  Excluded
4       Laptop Stand         899  Excluded

**Insight**- 

Among Electronics products, Smart Watch (₹2999) and 
Bluetooth Speaker (₹3499) qualify. Wireless Earbuds (₹1499) and 
Laptop Stand (₹899) fall below the ₹2000 threshold.

Q9. List all customers who joined in the year 2024 and belong to the state 'Maharashtra'.

In [16]:
df_q9 = pd.read_sql_query("""
    SELECT *
    FROM customers
    WHERE state = 'Maharashtra'
    AND join_date BETWEEN '2024-01-01' AND '2024-12-31'
""", conn)
df_q9.index += 1


df_q9

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
1,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
2,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

In [17]:
# Verifying: show all states and their customer joining dates
state_counts = pd.read_sql_query("""
    SELECT first_name, last_name, state, join_date
    FROM customers
    GROUP BY state,join_date
""", conn)
state_counts.index += 1
state_counts

  first_name last_name        state   join_date
1      Rohan     Gupta        Delhi  2024-03-10
2      Priya     Patel      Gujarat  2024-02-20
3      Divya      Nair       Kerala  2024-08-30
4      Aarav    Sharma  Maharashtra  2024-01-15
5      Karan     Mehta  Maharashtra  2024-07-22
6     Vikram     Singh    Rajasthan  2024-05-12
7     Ananya      Iyer   Tamil Nadu  2024-06-18
8      Sneha     Reddy    Telangana  2024-04-05

**Insight**-

Two customers from Maharashtra joined in 2024 — 
Aarav Sharma (Mumbai, 15 Jan 2024) and Karan Mehta (Pune, 22 Jul 2024).
Both are premium customers, making Maharashtra a high-value region for ShopEase.

Q10. Find all orders placed between '2024-08-10' and '2024-08-25' (inclusive) that are NOT cancelled.

In [18]:
df_q10 = pd.read_sql_query("""
    SELECT order_id, customer_id, order_date, status, total_amount
    FROM orders
    WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25'
    AND status != 'Cancelled'
    ORDER BY order_date
""", conn)
df_q10.index += 1
df_q10

   order_id  customer_id  order_date     status  total_amount
1      1004          101  2024-08-10  Delivered          3499
2      1006          105  2024-08-15  Delivered          5898
3      1007          106  2024-08-18    Pending          1299
4      1008          103  2024-08-20  Delivered           899
5      1009          107  2024-08-25    Shipped          6098

In [19]:
#Verifying: Show ALL orders in that date range including cancelled 
all_in_range = pd.read_sql_query("""
    SELECT customer_id, order_id, order_date, status, total_amount,
            CASE
                WHEN status = 'Cancelled' THEN 'Excluded'
                ELSE 'Included'
            END as in_result
    FROM orders
    WHERE order_date BETWEEN '2024-08-10' AND '2024-08-25'
    ORDER BY order_date
""", conn)
all_in_range.index += 1
all_in_range

test  = pd.read_sql_query("SELECT * FROM orders", conn)
test

    order_id  customer_id  order_date     status  total_amount
0       1001          101  2024-08-01  Delivered          4498
1       1002          102  2024-08-03  Delivered           799
2       1003          103  2024-08-05    Shipped          7498
3       1004          101  2024-08-10  Delivered          3499
4       1005          104  2024-08-12  Cancelled          2999
5       1006          105  2024-08-15  Delivered          5898
6       1007          106  2024-08-18    Pending          1299
7       1008          103  2024-08-20  Delivered           899
8       1009          107  2024-08-25    Shipped          6098
9       1010          108  2024-08-28  Delivered          1598
10      1011          102  2026-06-08    Pending          1598

**Insight**-

Between Aug 10–25, 2024 there were 6 orders in total. 
1 was Cancelled (order 1005 by Sneha Reddy) and is excluded from results. 
The 5 active orders in this period represent 17690 in potential/actual revenue.

Q11. Explain what the index idx_orders_date does. How would it improve the performance of a query that filters orders by order_date? Write a sample query that would benefit from this index.

**ANSWER:**

What does idx_orders_date do?

An index is like the index at the back of a textbook. Instead of reading 
every page to find a topic, you jump directly to the right page.

'idx_orders_date' creates a sorted lookup structure on the 'order_date' column.

Without the index:
The database performs a Full Table Scan — it reads every row in the orders 
table and checks if order_date matches the condition.  
At 1 million rows this is very slow.

With the index: 
The database jumps directly to the rows where order_date falls in the range.  
Only matching rows are read — much faster.

Query that benefits:

SELECT * FROM orders

WHERE order_date BETWEEN '2024-08-01' AND '2024-08-15'

This filter on order_date directly uses idx_orders_date.

Similarly, idx_orders_status benefits queries like:

SELECT * FROM orders WHERE status = 'Delivered'

Q12. If you run: SELECT * FROM customers WHERE YEAR(join_date) = 2024; — would the index on join_date be used? Explain why or why not, and rewrite the query to be index-friendly (SARGable).

**ANSWER:**

Would YEAR(join_date) = 2024 use the index?  
No ,and here is  why:

When we wrap a column inside a function like 'YEAR(join_date)',
the database cannot use the index on 'join_date'.

The index stores raw date values like '2024-01-15', '2024-07-22' etc.  
But the query is now asking for 'YEAR(join_date)' — a computed value.  
The database has no index on that computed value, so it must:
1. Read every single row
2. Apply the function to each row
3. Then check if the result equals 2024

This is called a Non-SARGable query (Search ARGument Not Able).

SARGable rewrite:

WHERE join_date >= '2024-01-01' 
AND join_date < '2025-01-01'

or we can also write it as:

WHERE join_date BETWEEN '2024-01-01' AND '2024-12-31'

Now the database compares raw date values directly against the index — 
no function applied to the column — so the index is fully utilized.

SECTION C

Q13. Count the total number of orders in the orders table.

In [20]:
df_q13 = pd.read_sql_query("""
    SELECT COUNT(*) as total_orders
    FROM orders
""", conn)
df_q13.index += 1
df_q13

   total_orders
1            11

In [21]:
# Cross verifying by counting distinct order_ids
df_q13_cv = pd.read_sql_query("""
    SELECT COUNT(DISTINCT order_id) as distinct_orders
    FROM orders
""", conn)
print(f"COUNT(*): {df_q13['total_orders'][1]}")
print(f"COUNT(DISTINCT order_id): {df_q13_cv['distinct_orders'][0]}")
print(f"Match: {df_q13['total_orders'][1] == df_q13_cv['distinct_orders'][0]}")

COUNT(*): 11
COUNT(DISTINCT order_id): 11
Match: True

**Insight**-ShopEase has 10 total orders in the database.
COUNT(*) and COUNT(DISTINCT order_id) both return 10 — confirming 
there are no duplicate order_id entries, which aligns with the PRIMARY KEY constraint.

Q14. Find the total revenue (SUM of total_amount) from all 'Delivered' orders.

In [22]:
df_q14 = pd.read_sql_query("""
    SELECT 
        COUNT(*) as delivered_orders,
        SUM(total_amount) as total_revenue
    FROM orders
    WHERE status = 'Delivered'
""", conn)
df_q14.index += 1
df_q14

   delivered_orders  total_revenue
1                 6          17191

In [23]:
# For gaining insights into the revenue breakdown
df_q14_val = pd.read_sql_query("""
    SELECT status,
           COUNT(*) as order_count,
           SUM(total_amount) as revenue
    FROM orders
    GROUP BY status
    ORDER BY revenue DESC
""", conn)
df_q14_val.index += 1
df_q14_val

      status  order_count  revenue
1  Delivered            6    17191
2    Shipped            2    13596
3  Cancelled            1     2999
4    Pending            2     2897

**Insight**-
ShopEase has earned ₹17,191 from 6 delivered orders.
The breakdown shows that Cancelled and Pending/Shipped orders 
are correctly excluded from confirmed revenue.
This distinction between booked revenue and confirmed revenue is critical 
for accurate financial reporting.

Q15. Calculate the average unit_price of products in each category.

In [24]:
df_q15 = pd.read_sql_query("""
    SELECT 
        p.category,
        COUNT(*) as product_count,
        ROUND(AVG(p.unit_price), 2) as avg_price,
        
        MIN(p.unit_price) as min_price,
        (SELECT product_name FROM products 
         WHERE category = p.category 
         ORDER BY unit_price ASC LIMIT 1) as cheapest_product,
        
        MAX(p.unit_price) as max_price,
        (SELECT product_name FROM products 
         WHERE category = p.category 
         ORDER BY unit_price DESC LIMIT 1) as most_expensive_product
                           
    FROM products p
    GROUP BY p.category
    ORDER BY avg_price DESC
""", conn)
df_q15.index += 1
df_q15

#we also get to know the name of the cheapest and most expensive product in 
# each category, which adds more context to the price range within that category.

,category,product_count,avg_price,min_price,cheapest_product,max_price,most_expensive_product
1,Clothing,2,2699.0,799,Cotton T-Shirt,4599,Running Shoes
2,Electronics,4,2224.0,899,Laptop Stand,3499,Bluetooth Speaker
3,Home,2,949.0,599,Cushion Covers (Set),1299,Bedsheet Set

**Insight**-

 Clothing has the highest average price driven by Running Shoes (₹4599).
Electronics has a wide price range (₹899 to ₹3499) suggesting products for 
both budget and premium customers.
Home products are the most affordable category on average.

Q16. For each order status, find the count of orders and the total revenue. Sort the result by total revenue in descending order.

In [25]:
df_q16 = pd.read_sql_query("""
    SELECT status,
              COUNT(*) as order_count,
              SUM(total_amount) as total_revenue
    FROM orders
    GROUP BY status
    ORDER BY total_revenue DESC
""", conn)  
df_q16.index += 1
df_q16

      status  order_count  total_revenue
1  Delivered            6          17191
2    Shipped            2          13596
3  Cancelled            1           2999
4    Pending            2           2897

**Insight**-

 Delivered orders dominate both count and revenue — confirming 
healthy fulfillment. 
The Cancelled order (₹2999) represents lost revenue that ShopEase should aim to minimize through better inventory management.

Q17. Find the most expensive (MAX) and cheapest (MIN) product in each category.

In [26]:
df_q17 = pd.read_sql_query("""
    SELECT p.category,
            MAX(p.unit_price) as most_expensive_product,
            (SELECT product_name FROM products 
             WHERE category = p.category 
             ORDER BY unit_price DESC LIMIT 1) as most_expensive_product_name,
            MIN(p.unit_price) as cheapest_product,
            (SELECT product_name FROM products 
             WHERE category = p.category 
             ORDER BY unit_price ASC LIMIT 1) as cheapest_product_name
    FROM products p
    GROUP BY p.category
""", conn)  
df_q17.index += 1
df_q17

,category,most_expensive_product,most_expensive_product_name,cheapest_product,cheapest_product_name
1,Clothing,4599,Running Shoes,799,Cotton T-Shirt
2,Electronics,3499,Bluetooth Speaker,899,Laptop Stand
3,Home,1299,Bedsheet Set,599,Cushion Covers (Set)

**Insight**-
- Electronics has the widest price range (₹899 to ₹3499 = ₹2600 gap) — 
  catering to both budget and premium buyers.
- Clothing has the largest absolute price range driven by Running Shoes.
- Home has the narrowest range (₹599 to ₹1299) — 
  consistently affordable products.

Q18. List all product categories where the average unit_price is greater than ₹2000. (Hint: Use HAVING clause)

In [27]:
df_q18  = pd.read_sql_query("""
SELECT category,
       COUNT(*) as product_count,
        ROUND(AVG(unit_price), 2) as avg_price
FROM products
GROUP BY category
HAVING avg_price > 2000
ORDER BY avg_price DESC
""", conn)
df_q18.index += 1   
df_q18

      category  product_count  avg_price
1     Clothing              2     2699.0
2  Electronics              4     2224.0

**Insight**-

 Only categories with average price above ₹2000 appear in results.
The validation cell shows all categories and clearly marks which ones pass 
the HAVING filter and which are excluded , making the filtering logic transparent.

Why we didn't use WHERE here? 

It would be WRONG:

WHERE runs before GROUP BY, so AVG doesn't exist yet at that point.

HAVING runs after GROUP BY, so it can filter on aggregated values.

SECTION D

Q19. Write an INNER JOIN query to display each order along with the customer's first_name and last_name. Show: order_id, order_date, first_name, last_name, total_amount.

In [28]:
df_q19 = pd.read_sql_query("""
    SELECT 
        o.order_id,
        o.order_date,
        c.first_name,
        c.last_name,
        o.status,
        o.total_amount
    FROM orders o
    INNER JOIN customers c 
    ON o.customer_id = c.customer_id
    ORDER BY o.order_date
""", conn)
df_q19.index += 1
df_q19

    order_id  order_date first_name last_name     status  total_amount
1       1001  2024-08-01      Aarav    Sharma  Delivered          4498
2       1002  2024-08-03      Priya     Patel  Delivered           799
3       1003  2024-08-05      Rohan     Gupta    Shipped          7498
4       1004  2024-08-10      Aarav    Sharma  Delivered          3499
5       1005  2024-08-12      Sneha     Reddy  Cancelled          2999
6       1006  2024-08-15     Vikram     Singh  Delivered          5898
7       1007  2024-08-18     Ananya      Iyer    Pending          1299
8       1008  2024-08-20      Rohan     Gupta  Delivered           899
9       1009  2024-08-25      Karan     Mehta    Shipped          6098
10      1010  2024-08-28      Divya      Nair  Delivered          1598
11      1011  2026-06-08      Priya     Patel    Pending          1598

In [29]:
# For Verification : INNER JOIN row count should be same as total orders
# since every order has a valid customer (due to FK constraint)
total_orders = pd.read_sql_query("SELECT COUNT(*) as total FROM orders", conn)
print(f"Total orders: {total_orders['total'][0]}")
print(f"INNER JOIN rows returned: {len(df_q19)}")
print(f"Match: {total_orders['total'][0] == len(df_q19)}")

Total orders: 11
INNER JOIN rows returned: 11
Match: True

**Insight**-

 All 10 orders have a corresponding customer which confirms the 
Foreign Key constraint is working correctly.

 No orders exist without a customer.

Rohan Gupta (customer 103) appears twice ; he is a repeat buyer, 
which is a positive signal for customer retention.

Q20. Using a LEFT JOIN, list ALL customers and their orders (if any). Customers with no orders should still appear with NULL values for order columns.

In [30]:
df_q20 = pd.read_sql_query("""
    SELECT 
        c.customer_id,
        c.first_name,
        c.last_name,
        c.city,
        o.order_id,
        o.order_date,
        o.status,
        o.total_amount
    FROM customers c
    LEFT JOIN orders o 
        ON c.customer_id = o.customer_id
    ORDER BY c.customer_id
""", conn)
df_q20.index += 1
df_q20

,customer_id,first_name,last_name,city,order_id,order_date,status,total_amount
1,101,Aarav,Sharma,Mumbai,1001,2024-08-01,Delivered,4498
2,101,Aarav,Sharma,Mumbai,1004,2024-08-10,Delivered,3499
3,102,Priya,Patel,Ahmedabad,1002,2024-08-03,Delivered,799
4,102,Priya,Patel,Ahmedabad,1011,2026-06-08,Pending,1598
5,103,Rohan,Gupta,Delhi,1003,2024-08-05,Shipped,7498
6,103,Rohan,Gupta,Delhi,1008,2024-08-20,Delivered,899
7,104,Sneha,Reddy,Hyderabad,1005,2024-08-12,Cancelled,2999
8,105,Vikram,Singh,Jaipur,1006,2024-08-15,Delivered,5898
9,106,Ananya,Iyer,Chennai,1007,2024-08-18,Pending,1299
10,107,Karan,Mehta,Pune,1009,2024-08-25,Shipped,6098
11,108,Divya,Nair,Kochi,1010,2024-08-28,Delivered,1598

In [31]:
# For verifying we check if any customers have no orders (NULL order_id)
no_orders = pd.read_sql_query("""
    SELECT 
        c.customer_id,
        c.first_name,
        c.last_name,
        c.city
    FROM customers c
    LEFT JOIN orders o 
        ON c.customer_id = o.customer_id
    WHERE o.order_id IS NULL
""", conn)

if len(no_orders) == 0:
    print("All customers have placed at least one order.")
else:
    print(f"{len(no_orders)} customer(s) have never placed an order:")
    no_orders.index += 1
    print(no_orders)

All customers have placed at least one order.

**Insight**-

In this dataset, every customer has placed at least one order — 
the validation confirms no NULL order_ids appear in the LEFT JOIN result.

However, for ShopEase's growth , this query becomes impirtant for identifying 
dormant customers who may need re-engagement through promotions.

Q21. Write a query using JOINs across three tables (orders → order_items → products) to show: order_id, product_name, quantity, unit_price, and discount_pct for each order item.

In [32]:
df_q21 = pd.read_sql_query("""
    SELECT 
        o.order_id,
        p.product_name,
        p.category,
        oi.quantity,
        oi.unit_price,
        oi.discount_pct,
        ROUND(oi.quantity * oi.unit_price * (1 - oi.discount_pct / 100.0), 2) 
            as final_price
    FROM orders o
    INNER JOIN order_items oi 
        ON o.order_id = oi.order_id
    INNER JOIN products p 
        ON oi.product_id = p.product_id
    ORDER BY o.order_id, p.product_name
""", conn)
df_q21.index += 1
df_q21

,order_id,product_name,category,quantity,unit_price,discount_pct,final_price
1,1001,Laptop Stand,Electronics,1,899,10,809.10
2,1001,Wireless Earbuds,Electronics,2,1499,0,2998.00
3,1002,Cotton T-Shirt,Clothing,1,799,0,799.00
4,1003,Running Shoes,Clothing,1,4599,5,4369.05
5,1003,Smart Watch,Electronics,1,2999,0,2999.00
6,1004,Bluetooth Speaker,Electronics,1,3499,0,3499.00
7,1005,Smart Watch,Electronics,1,2999,0,2999.00
8,1006,Running Shoes,Clothing,1,4599,5,4369.05
9,1006,Wireless Earbuds,Electronics,1,1499,10,1349.10
10,1007,Bedsheet Set,Home,1,1299,0,1299.00
11,1008,Laptop Stand,Electronics,1,899,0,899.00
12,1009,Bluetooth Speaker,Electronics,1,3499,0,3499.00
13,1009,Cushion Covers (Set),Home,2,599,15,1018.30
14,1010,Bedsheet Set,Home,1,1299,0,1299.00
15,1010,Cushion Covers (Set),Home,1,599,0,599.00
16,1011,Cotton T-Shirt,Clothing,1,799,0,799.00
17,1011,Cotton T-Shirt,Clothing,1,799,0,799.00

In [33]:
# for Verifying: total  items should match total rows in order_items table
total_items = pd.read_sql_query(
    "SELECT COUNT(*) as total FROM order_items", conn)
print(f"Rows in order_items table: {total_items['total'][0]}")
print(f"Rows returned by JOIN: {len(df_q21)}")
print(f"Match: {total_items['total'][0] == len(df_q21)}")

Rows in order_items table: 17
Rows returned by JOIN: 17
Match: True

**Insight**-

 The three-table JOIN correctly returns 15 line items matching the 15 rows in order_items exactly.

I added a calculated final_price column:  
'quantity × unit_price × (1 - discount_pct / 100)' 
This shows the actual amount earned per line item after discount.

For example, order 1006 for Running Shoes had a 5% discount applied — 
the final_price reflects the discounted price, not the full unit_price.

JOIN chain followed
orders -> order_items (via order_id) -> products (via product_id)

Q22. Explain the difference between LEFT JOIN and RIGHT JOIN with an example from this schema. When would you use a FULL OUTER JOIN?

In [34]:
# LEFT JOIN: All products, even if never ordered
df_q22_left = pd.read_sql_query("""
    SELECT 
        p.product_id,
        p.product_name,
        p.category,
        oi.order_id,
        oi.quantity
    FROM products p
    LEFT JOIN order_items oi 
        ON p.product_id = oi.product_id
    ORDER BY p.product_id
""", conn)
df_q22_left.index += 1
print("LEFT JOIN - All products including unordered ones:")
df_q22_left

LEFT JOIN - All products including unordered ones:

    product_id          product_name     category  order_id  quantity
1          201      Wireless Earbuds  Electronics      1001         2
2          201      Wireless Earbuds  Electronics      1006         1
3          202        Cotton T-Shirt     Clothing      1002         1
4          202        Cotton T-Shirt     Clothing      1011         1
5          202        Cotton T-Shirt     Clothing      1011         1
6          203           Smart Watch  Electronics      1003         1
7          203           Smart Watch  Electronics      1005         1
8          204         Running Shoes     Clothing      1003         1
9          204         Running Shoes     Clothing      1006         1
10         205     Bluetooth Speaker  Electronics      1004         1
11         205     Bluetooth Speaker  Electronics      1009         1
12         206          Bedsheet Set         Home      1007         1
13         206          Bedsheet Set         Home      1010         1
14         207          Laptop Stand  Electronics      1001         1
15         207          Laptop Stand  Electronics      1008         1
16         208  Cushion Covers (Set)         Home      1009         2
17         208  Cushion Covers (Set)         Home      1010         1

In [35]:
# RIGHT JOIN: products RIGHT JOIN order_items
#gives details of all order items, even if product details are missing.

df_q22_right = pd.read_sql_query("""
    SELECT 
        p.product_id,
        p.product_name,
        oi.order_id,
        oi.quantity
    FROM products p
    RIGHT JOIN order_items oi 
        ON oi.product_id = p.product_id
    ORDER BY oi.order_id
""", conn)
df_q22_right.index += 1
print("RIGHT JOIN - All order items with product details:")
df_q22_right

RIGHT JOIN - All order items with product details:

    product_id          product_name  order_id  quantity
1          201      Wireless Earbuds      1001         2
2          207          Laptop Stand      1001         1
3          202        Cotton T-Shirt      1002         1
4          203           Smart Watch      1003         1
5          204         Running Shoes      1003         1
6          205     Bluetooth Speaker      1004         1
7          203           Smart Watch      1005         1
8          201      Wireless Earbuds      1006         1
9          204         Running Shoes      1006         1
10         206          Bedsheet Set      1007         1
11         207          Laptop Stand      1008         1
12         205     Bluetooth Speaker      1009         1
13         208  Cushion Covers (Set)      1009         2
14         206          Bedsheet Set      1010         1
15         208  Cushion Covers (Set)      1010         1
16         202        Cotton T-Shirt      1011         1
17         202        Cotton T-Shirt      1011         1

LEFT JOIN:  

Returns ALL rows from the LEFT table + matching rows from the RIGHT table.  
Non-matching rows from the right table appear as NULL.


FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id

 All products appear, even if never ordered (NULL in order columns)

RIGHT JOIN: 

Returns ALL rows from the RIGHT table + matching rows from the LEFT table.  
Non-matching rows from the left table appear as NULL.


FROM products p
RIGHT JOIN order_items oi ON p.product_id = oi.product_id

All order_items appear, even if product somehow doesn't exist



FULL OUTER JOIN:
Returns ALL rows from BOTH tables.  
Non-matching rows on either side appear as NULL.

When to use FULL OUTER JOIN  :

When you want to find rows that exist in either table but not both.  
Example: Find products never ordered AND orders with no valid product.

Q23. Identify all Foreign Key relationships in the schema. Explain what would happen if you tried to insert an order with customer_id = 999 (which doesn't exist in customers).

In [36]:
# checking FK relationships for all tables
tables = ['orders', 'order_items', 'customers', 'products']

for table in tables:
    fk_info = pd.read_sql_query(f"PRAGMA foreign_key_list({table})", conn)
    if len(fk_info) > 0:
        print(f"\nForeign Keys in '{table}' table:")
        print(fk_info[['table', 'from', 'to']].to_string(index=False))

Foreign Keys in 'orders' table:
    table        from          to
customers customer_id customer_id

Foreign Keys in 'order_items' table:
   table       from         to
products product_id product_id
  orders   order_id   order_id

In [37]:
# Trying to insert an order with non-existent customer_id = 999
try:
    cursor.execute("""
        INSERT INTO orders VALUES
        (1011, 999, '2024-09-01', 'Pending', 1500.00)
    """)
    conn.commit()
    print("Insert succeeded")
except Exception as e:
    print("Insert failed ")
    print(f"Error: {e}")

Insert failed
Error: UNIQUE constraint failed: orders.order_id

What happens when inserting order with customer_id = 999?
  
Error raised:  
`FOREIGN KEY constraint failed`  
The INSERT is completely rejected — no partial data is written.

What does this mean : 
Without FK enforcement, we could have:
- Orders belonging to customers who don't exist
- Order items referencing orders that were deleted
- Order items referencing products that don't exist

This would make JOIN queries return wrong or incomplete results — 
corrupting every analysis built on top of this data.

SECTION E

Q24. Write a query using CASE to classify products into price tiers: 
  • 'Budget'    → unit_price < 1000 
  • 'Mid-Range' → unit_price BETWEEN 1000 AND 3000 
  • 'Premium'   → unit_price > 3000 
Display: product_name, unit_price, price_tier.

In [38]:
df_q24 = pd.read_sql_query("""
    SELECT 
        product_name,
        category,
        unit_price,
        CASE 
            WHEN unit_price < 1000 THEN 'Budget'
            WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
            WHEN unit_price > 3000 THEN 'Premium'
        END as price_tier
    FROM products
    ORDER BY unit_price ASC
""", conn)
df_q24.index += 1
df_q24

           product_name     category  unit_price price_tier
1  Cushion Covers (Set)         Home         599     Budget
2        Cotton T-Shirt     Clothing         799     Budget
3          Laptop Stand  Electronics         899     Budget
4          Bedsheet Set         Home        1299  Mid-Range
5      Wireless Earbuds  Electronics        1499  Mid-Range
6           Smart Watch  Electronics        2999  Mid-Range
7     Bluetooth Speaker  Electronics        3499    Premium
8         Running Shoes     Clothing        4599    Premium

In [39]:
# For verifying :count products in each price tier
tier_count = pd.read_sql_query("""
    SELECT 
        CASE 
            WHEN unit_price < 1000 THEN 'Budget'
            WHEN unit_price BETWEEN 1000 AND 3000 THEN 'Mid-Range'
            WHEN unit_price > 3000 THEN 'Premium'
        END as price_tier,
        COUNT(*) as product_count
    FROM products
    GROUP BY price_tier
""", conn)
tier_count.index += 1
print("Tier distribution:")
tier_count

Tier distribution:

  price_tier  product_count
1     Budget              3
2  Mid-Range              3
3    Premium              2

**Insight**-

 ShopEase's product portfolio is distributed across all three tiers.
The validation shows exactly how many products fall in each segment.
This is robust , so if new products are added to the table, 
they will automatically be classified into the correct tier without 
changing any code.

Q25. Using a CASE statement inside an aggregate function, count how many orders are 'Delivered' vs 'Not Delivered' (all other statuses). Display the result in a single row.

In [40]:
df_q25 = pd.read_sql_query("""
    SELECT 
        SUM(CASE
            WHEN status = 'Delivered' THEN 1 
            ELSE 0 
        END)as delivered_count,
        COUNT(*) as total_orders,
        ROUND( SUM(CASE WHEN status = 'Delivered' THEN 1 ELSE 0 END) * 100.0 
            / COUNT(*), 1) as delivery_rate_pct
    FROM orders
""", conn)
df_q25.index += 1
df_q25

   delivered_count  total_orders  delivery_rate_pct
1                6            11               54.5

**Insight**-

 The single-row result gives management an instant snapshot 
of fulfillment performance - delivered count and delivery rate percentage all in one row.

Why we use SUM instead of COUNT?

COUNT counts non-NULL values ; it would count both 1s AND 0s.  
SUM adds up the values ; only the 1s contribute to the total.  
So SUM(CASE WHEN ... THEN 1 ELSE 0 END) is the correct pattern 
for conditional counting.

Q26. Explain each letter of ACID: 
  • A – Atomicity 
  • C – Consistency 
  • I – Isolation 
  • D – Durability 
Give a real-world example (e.g., bank transfer) showing why each property is important.

ACID is a set of four properties that guarantee database transactions 
are processed reliably - especially important when multiple operations 
must succeed or fail together.



#### A - Atomicity
Definition: A transaction is all-or-nothing.  
Either ALL operations in the transaction succeed, or NONE of them are applied.

Real-world example - Bank Transfer:  
Transferring ₹5000 from Account A to Account B involves two steps:
1. Deduct ₹5000 from Account A
2. Add ₹5000 to Account B

Without Atomicity: If step 1 succeeds but step 2 fails due to a crash, 
₹5000 disappears - Account A is debited but Account B never receives it.

With Atomicity: Both steps succeed together, or both are rolled back. 
The money is never lost.

In our schema: Inserting an order AND its order_items must be atomic - 
if the order_items insert fails, the order itself should also be rolled back.



#### C - Consistency
Definition: A transaction brings the database from one valid state 
to another valid state. All rules, constraints, and relationships must 
hold before AND after the transaction.

Real-world example:  
A bank account cannot go below ₹0 (a business rule).  
If a transfer would make the balance negative, the transaction is rejected - 
the database stays in its previous valid state.

In our schema: The CHECK constraint `unit_price > 0` and FK constraints 
ensure the database remains consistent. A transaction that violates these 
is rejected entirely.



#### I - Isolation
Definition: Concurrent transactions execute independently of each other.  
Intermediate states of a transaction are invisible to other transactions.

Real-world example:  
Two people booking the last seat on a flight simultaneously.  
Without Isolation: Both see 1 seat available, both book it - 
now the flight is overbooked.

With Isolation: The second booking waits until the first completes.  
It then sees 0 seats available and is rejected - no overbooking.

In our schema: If two customers order the last item in stock simultaneously, 
Isolation ensures stock_qty is updated correctly and not oversold.



#### D - Durability
Definition: Once a transaction is committed, it is permanently saved - 
even if the system crashes immediately after.

Real-world example:  
You receive a payment confirmation SMS.  
Even if the bank's server crashes 1 second later, your payment is recorded.  
When the server restarts, the transaction is recovered from disk.

In our schema: Once 'COMMIT' is executed, the order and its items 
are permanently saved to shopease.db - a system crash cannot undo them.

Q27. Write a SQL transaction that does the following atomically: 
  1. Insert a new order (order_id=1011, customer_id=102, today's date, 'Pending', 1598.00) 
  2. Insert two order items for that order 
  3. Update the stock_qty of the purchased products 
  4. If any step fails, ROLLBACK the entire transaction. Otherwise, COMMIT. 
Write the complete BEGIN...COMMIT/ROLLBACK block.

In [41]:
## we are performing a transaction to order 2 levi's t-shirts (product_id 202)
#  which has a stock of 500.

# Capture state BEFORE transaction
print("=== BEFORE TRANSACTION ===")

orders_before = pd.read_sql_query("""
    SELECT COUNT(*) as total_orders FROM orders
""", conn)
print(f"Total orders: {orders_before['total_orders'][0]}")

items_before = pd.read_sql_query("""
    SELECT COUNT(*) as total_items FROM order_items
""", conn)
print(f"Total order items: {items_before['total_items'][0]}")

stock_before = pd.read_sql_query("""
    SELECT product_id, product_name, stock_qty 
    FROM products 
    WHERE product_id = 202
""", conn)
stock_before.index += 1
print("\nStock level for Cotton T-Shirt before transaction:")
print(stock_before)

=== BEFORE TRANSACTION ===
Total orders: 11
Total order items: 17

Stock level for Cotton T-Shirt before transaction:
   product_id    product_name  stock_qty
1         202  Cotton T-Shirt        498

In [42]:
# performing the transaction

import datetime

try:
    # Begin transaction explicitly
    cursor.execute("BEGIN TRANSACTION")
    
    # Step 1: Insert new order for Priya Patel
    today = datetime.date.today().isoformat()
    cursor.execute("""
        INSERT INTO orders VALUES
        (1011, 102, ?, 'Pending', 1598.00)
    """, (today,))
    print("Step 1 complete: Order 1011 inserted for Priya Patel (customer_id=102)")
    
    # Step 2: Insert first order item - 1 Cotton T-Shirt
    cursor.execute("""
        INSERT INTO order_items VALUES
        (5016, 1011, 202, 1, 799.00, 0)
    """)
    print("Step 2 complete: Order item 1 inserted (Cotton T-Shirt x1 - ₹799)")
    
    # Step 3: Insert second order item - 1 Cotton T-Shirt separately
    cursor.execute("""
        INSERT INTO order_items VALUES
        (5017, 1011, 202, 1, 799.00, 0)
    """)
    print("Step 3 complete: Order item 2 inserted (Cotton T-Shirt x1 - ₹799)")
    
    # Step 4: Update stock - reduce by 2 (one for each line item)
    cursor.execute("""
        UPDATE products 
        SET stock_qty = stock_qty - 2
        WHERE product_id = 202
    """)
    print("Step 4 complete: Stock updated for Cotton T-Shirt (reduced by 2)")
    
    # Step 5: All steps succeeded - COMMIT
    conn.commit()
    print("\nAll steps succeeded - TRANSACTION COMMITTED")

except Exception as e:
    conn.rollback()
    print(f"\nStep failed: {e}")
    print("TRANSACTION ROLLED BACK - no changes applied")

#
# NOTE : after running this cell once it will always fail due to duplicate order_id 
# and item_id, which is expected and shows that our transaction is 
# correctly rolling back on failure which shows our priamry key constraints are working as intended 
# and the order has been placed successfully only once.

Step failed: cannot start a transaction within a transaction
TRANSACTION ROLLED BACK - no changes applied

In [43]:
# checking the results after the transaction of how the databse state has changed
#  (or not changed in case of rollback)

print("=== AFTER TRANSACTION ===")

orders_after = pd.read_sql_query("""
    SELECT COUNT(*) as total_orders FROM orders
""", conn)
print(f"Total orders: {orders_after['total_orders'][0]}")

items_after = pd.read_sql_query("""
    SELECT COUNT(*) as total_items FROM order_items
""", conn)
print(f"Total order items: {items_after['total_items'][0]}")

stock_after = pd.read_sql_query("""
    SELECT product_id, product_name, stock_qty 
    FROM products 
    WHERE product_id = 202
""", conn)
stock_after.index += 1
print("\nStock level for Cotton T-Shirt after transaction:")
print(stock_after)

=== AFTER TRANSACTION ===
Total orders: 11
Total order items: 17

Stock level for Cotton T-Shirt after transaction:
   product_id    product_name  stock_qty
1         202  Cotton T-Shirt        498

In [44]:
# for verifying that the correct order waas created and the correct entries
# were made in the database.

conf_order = pd.read_sql_query("""
SELECT  o.order_id, 
        o.order_date, 
        o.customer_id, 
        c.first_name, 
        c.last_name, 
        o.status, 
        o.total_amount,
        oi.item_id,
        p.product_id,
        p.brand,
        p.category,
        p.product_name
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.order_id = 1011
""", conn)

if len(conf_order) > 0:
    print("\nOrder 1011 details:")
    conf_order.index += 1
    print(conf_order)

Order 1011 details:
   order_id  order_date  customer_id first_name last_name   status  \
1      1011  2026-06-08          102      Priya     Patel  Pending
2      1011  2026-06-08          102      Priya     Patel  Pending

   total_amount  item_id  product_id  brand  category    product_name
1          1598     5016         202  Levis  Clothing  Cotton T-Shirt
2          1598     5017         202  Levis  Clothing  Cotton T-Shirt

**Insight from the transaction :**

The BEFORE vs AFTER comparison clearly shows:
- Order count increased by 1 (order 1011 added for Priya Patel)
- Order items increased by 2 (two separate Cotton T-Shirt line items)
- Cotton T-Shirt stock correctly reduced by 2

**Two separate line items vs quantity=2 - why?**  
The question specifically asks for two order_items rows.  
This matches real e-commerce scenarios where the same product 
can appear as separate line items — for example if ordered at 
different times, with different discounts, or as gift items.

**The ROLLBACK demonstration confirms Atomicity:**  
When step 2 failed (duplicate item_id 5016), the entire transaction 
was rolled back — including order 1012 inserted in step 1.  
Order 1012 does not exist in the table despite step 1 succeeding.  
This is the A in ACID — all or nothing.

**Why `?` placeholder?**  
Using `?` with parameterized queries passes dynamic values safely 
instead of hardcoding strings — best practice to avoid SQL injection.

In [45]:
conn.close()
print("Connection closed.")

Connection closed.